// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiubM4xPmiHvnD9_fuiAEvnEAmsUoiCCs',
    appId: '1:650591894138:web:27ba27f32d80fcdd71d9c3',
    messagingSenderId: '650591894138',
    projectId: 'fir-78f74',
    authDomain: 'fir-78f74.firebaseapp.com',
    storageBucket: 'fir-78f74.appspot.com',
    measurementId: 'G-M6RM945L1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJTVG_2E-iqy5irRA9a521tttKdrAanQ',
    appId: '1:650591894138:android:0f37c5fb0ca7c9fe71d9c3',
    messagingSenderId: '650591894138',
    projectId: 'fir-78f74',
    storageBucket: 'fir-78f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbCT7Nd9SVZ_u0jQLZ1eN-mDU70hm8u4',
    appId: '1:650591894138:ios:b1f6910e12ad4b0e71d9c3',
    messagingSenderId: '650591894138',
    projectId: 'fir-78f74',
    storageBucket: 'fir-78f74.appspot.com',
    iosBundleId: 'com.example.workWaveConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFbCT7Nd9SVZ_u0jQLZ1eN-mDU70hm8u4',
    appId: '1:650591894138:ios:9e0971b78eb4ab4871d9c3',
    messagingSenderId: '650591894138',
    projectId: 'fir-78f74',
    storageBucket: 'fir-78f74.appspot.com',
    iosBundleId: 'com.example.workWaveConnect.RunnerTests',
  );
}
